spring:
    application:
        name: dispatch-ui
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
server:
    port: 32901
eureka:
    instance:
      prefer-ip-address: true
ht.config.ui:
  baseUrl: http://172.16.200.120:32016/
  gatewayUrl: http://172.16.200.110:30111/
  changePwdUrl: http://172.16.200.110:30131/html/user/changePwdOther.html
  userInfoUpdate: http://172.16.200.110:30131/html/user/userInfoOther.html
  ruleServiceUrl: rule/config/
  ruleDroolsUrl: rule/drools/